before:
  hooks:
  - go mod download
archives:
- format: binary
  files:
  - none*
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"


builds:
- id: tfs_model_status_probe
  main: .
  binary: tfs_model_status_probe
  flags:
  - -tags=netgo
  ldflags:
  - -w
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm: [6]
