name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  citest:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Go Vet
      run: go vet -v ./...

    - name: Go Test
      run: go test -v .

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
